version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.1
executor: cypress/default
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          package-manager: 'npm'
          cypress-command: 'npm test'
          install-browsers: true